### ISSUE TITLE
use addMaskPlane for BRIGHT

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#137]
downstream codes will need to adapt

Also we will need to add this mask plane to calexp in real data after they are read

**Comment by beckermr** [comment]
What is this bit for and what do you mean here?

**Comment by esheldon** [comment]
BRIGHT marks bright stars. It is not part of the default set of mask planes in the stack.

But you can do this once you have a `MaskedImageF`
```
masked_image = MaskedImageF(100, 100)
masked_image.mask.addMaskPlane('BRIGHT')
```
this will add a new possible bit for this image (9 for the current default set which goes to 8).  Then we use get the value of BRIGHT using  `masked_image.mask.getPlaneBitMask('BRIGHT')` when we set the mask in the sim code.

The downstream coadd code then can also use `masked_image.mask.getPlaneBitMask('BRIGHT')` to get the value for interpolation etc,

**Comment by esheldon** [comment]
For real data we will be marking BRIGHT for stars, eventually.  We can follow the same procedure.  We can also add STREAK etc.

**Comment by beckermr** [comment]
Ahh great. Thanks for the explanation!
