### ISSUE TITLE
do not generate and return noise field with simulated exposures

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#141]
We are successfully generating these downstream now

Along with this, simplify the output to be a list of exposures per band, rather than a list of dicts with keys data and noise

**Comment by beckermr** [comment]
I'm confused by this. We are now adding sky backgrounds in these sims so that we can estimate noise from the images? Don't we need to handle units properly to get back to electrons or something?

**Comment by esheldon** [comment]
All I'm saying is that we will no longer return an example noise field from the sims, we require the processing codes to generate it.

I'm already doing this, I'm ignoring the noise field generated by the sim

**Comment by beckermr** [comment]
> I'm already doing this, I'm ignoring the noise field generated by the sim

Right. I am asking how exactly this process works for both the sims and the real data. I guess you use the weight map or variance image?

**Comment by beckermr** [comment]
Right ok. That all makes sense.
