### ISSUE TITLE
toImage should be given a CelestialCoord

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#15]
In `render_objs_with_psf_shear` the position being sent should be a `CelestialCoord` not a `PositionD`

**Comment by esheldon** [comment]
I'm seeing this problem when  using a TanWCS

**Comment by esheldon** [comment]
I imagine just dropping in a celestial for positionD could break the simple sim though

**Comment by beckermr** [comment]
Yeah we need rewrite everything using celestial coords from get go and just not support non-celestial stuff.

**Comment by esheldon** [comment]
not sure exactly what you have in mind, but feel free to work on the PR

**Comment by esheldon** [comment]
going to celestial coords makes your code for shearing the positions wrong I think.

If galsim knows how to do this internally, we can try to pull out that code, but easier would be to `galsim.Add` the objects and let galsim do its thing to get the positions right

**Comment by beckermr** [comment]
So galsim won’t know how to do this I think. It uses a single Jacobian when rendering images. Well have to shear the positions in something like the uv plane of the tangent projection.

**Comment by esheldon** [comment]
I'm not sure what it means "shear the positions in something like the uv plane of the tangent projection."

**Comment by esheldon** [comment]
Do you mean "shear the positions on the curved sky"?

**Comment by beckermr** [comment]
We cannot shear them on a curved sky or if we can, IDK the math. I am saying we shear them in a tangent plane about the center of the patch.
