### ISSUE TITLE
ModuleNotFoundError: No module named 'descwl'

### ISSUE THREAD

**Issue by arunkannawadi** [LSSTDESC/descwl-shear-sims#183]
This package seems to be importing `descwl` in [some places](https://github.com/LSSTDESC/descwl-shear-sims/blob/6e4a0baa6f664b5bc52b08b55614eaa58c8b0748/descwl_shear_sims/surveys.py#L2) which is not in LSSTDESC repository or elsewhere on Github. Has this been package been renamed, or is it installed locally in your dev environment?

**Comment by beckermr** [comment]
lsstdesc-weaklensingdeblending on conda

**Comment by arunkannawadi** [comment]
Just hunted it down as well. I'm doing a non-conda installation and getting into rabbit holes in sorting out the dependencies.
