### ISSUE TITLE
return properly centered PSF images

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/descwl-shear-sims#24]
Right now the returned PSF images do not have the subpixel offsets.

**Comment by esheldon** [comment]
please make it optional so I can run the same test I did but with just one thing changed, e.g. cosmics

**Comment by beckermr** [comment]
For sure, however I want to run tests without cosmics and with the offsets on. Do you have scripts together to do this somewhere or should I make my own? We should push them to one spot probably.

**Comment by esheldon** [comment]
I've got a script that does everything, sim, coadd, metadetect.

Want me to upload it to metadetect repo?

**Comment by beckermr** [comment]
Hmmmm, it feels like a new home is needed, but yeah in the metadetect repo is fine for now.
