### ISSUE TITLE
add cosmics to the noise images

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#25]
since we must run the cosmic finder to get the interpolation, I think we need to add them to the noise image too

and this reminds me, we need this to happen on 90 degree rotated versions too, which I think means we need, at this point, to put in 90 degree cosmics in the sim itself

**Comment by beckermr** [comment]
The bit mask has them marked, so I think the downstream coadding code should be adding them, not the sim gen code. Thoughts?

**Comment by beckermr** [comment]
I also think the coadding code should do the rotation, not the sim code.

**Comment by esheldon** [comment]
no, the interpolation happens when the cosmics are found and we need the interpolation to occur for the 90 deg rotated version

**Comment by beckermr** [comment]
Yes, but I am saying the code that adjust the exposures by adding the cosmics bits to the noise image should be in the coadding repo not here.

**Comment by beckermr** [comment]
These sims return a facsimile of what the stack might pass out from their equivalent of a DES final cut image. That is the API interface.
