### ISSUE TITLE
turning on cosmics we are getting zero detections in 15% of coadds

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#27]

**Comment by esheldon** [comment]
I meant zero detections in the coadds

**Comment by beckermr** [comment]
Do you have example images?

**Comment by esheldon** [comment]
This reproduces it on the second trial
```bash
python ~/git/metadetect/examples/lsst_sim.py \
    --cosmic-rays \
    --nepochs 1 \
    --noise 1 \
    --ntrial 2 \
    --seed 244714 \
    --output /tmp/test.fits
```

**Comment by esheldon** [comment]
Here you can see that a hot 10^18 pixel is left at the bottom
![example](https://user-images.githubusercontent.com/621661/72803999-70a80880-3c1d-11ea-8563-19ef60671661.png)

**Comment by esheldon** [comment]
that is, after "repair"

**Comment by beckermr** [comment]
Ahhhhh. So the cosmic ray finder misses the pixel and then the detections get mucked up.

We can turn down the cosmic ray level to "saturation" but this very well could be an issue in real data. 

We probably need an outlier masking step like we use in DES.

**Comment by esheldon** [comment]
the resulting coadd ends up looking like flat white image

**Comment by beckermr** [comment]
We should consult the stack folks on this. They must have processing steps that do this sort of thing.

**Comment by esheldon** [comment]
Its probably because it is near the edge; I bet they typically mask those areas

**Comment by esheldon** [comment]
(pure speculation)

**Comment by beckermr** [comment]
They have edge bit mask flags in the code. Maybe we should use them...

**Comment by esheldon** [comment]
before repair

![before](https://user-images.githubusercontent.com/621661/72804308-1e1b1c00-3c1e-11ea-93c0-fd24dad0183b.png)

after repair

![after](https://user-images.githubusercontent.com/621661/72804332-27a48400-3c1e-11ea-86d0-133d9245a2bf.png)

**Comment by esheldon** [comment]
there is a derivative involved with the CR finding, probably cannot be done at the edge

**Comment by beckermr** [comment]
We could also only draw cosmics in the center

**Comment by beckermr** [comment]
https://github.com/LSSTDESC/descwl-shear-sims/issues/28

**Comment by esheldon** [comment]
Yeah, that would probably fix it.  Or I can zero out edges in the coadd code before repair, which is a good test in any case.  I'll try it.

**Comment by esheldon** [comment]
I tried zeroing out a 2 pixel border and it fixed the case I posted above

**Comment by esheldon** [comment]
fixed by setting bits for the edge and updating the coadd code to ignore them
