### ISSUE TITLE
only draw cosmic rays away from edges

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/descwl-shear-sims#28]
The stack has trouble near the edges with the finder, so we should avoid them.

**Comment by esheldon** [comment]
Due to edge distortions (glowing edges in DES, but dimmer in LSST devices) the stack will not be working within some set of pixels from the edge.

In DES I think we typically mask 15 pixels.

**Comment by esheldon** [comment]
I think it is better to do it in the sim.  The coadd code will be taking in corrected images with bits set in the edge area.  We could set those bits.

**Comment by beckermr** [comment]
yup 100%

I plan to only draw cosmics away from the edges and set the edge mask bits here.

**Comment by esheldon** [comment]
We can draw them but we should mark them.

The edge bit is `Plane 4 -> EDGE` so 2**4 = 16

**Comment by esheldon** [comment]
although, we should use the mask plane code for that and get the value using the name EDGE

by the way I found "official" examples here:  http://doxygen.lsst.codes/stack/doxygen/x_masterDoxyDoc/afw_mask_planes.html

Note that they construct an example mask to do this

**Comment by beckermr** [comment]
I am hard coding the flags and then testing them upon import if the stack is around, but yes they will be consistent.

**Comment by esheldon** [comment]
we may not hear from those guys about the number of pixels to mask for a while due to the DESC meeting.  Shall we just go with 15 for now?

**Comment by beckermr** [comment]
sure

**Comment by beckermr** [comment]
I won't be able to make a PR for a few hours, feel free to go ahead or wait.

**Comment by esheldon** [comment]
Turns out setting EDGE didn't solve the issue with the cosmic ray finder.

I think we should, for now, not draw them near the edge as you originally suggested

**Comment by esheldon** [comment]
ok, we can now draw these anywhere we want, as long as we set the bitmask
