### ISSUE TITLE
make default coadd image odd in shape

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/descwl-shear-sims#36]
We need to test the code with this before we simply switch it over.

**Comment by esheldon** [comment]
What test did you have in mind, something beyond the current tests?

**Comment by esheldon** [comment]
I also want to note for posterity, that the motivation for this was so that specifically the case of no dithers would produce a perfectly matched grid between coadd and SE images

**Comment by beckermr** [comment]
I mostly want to read through the code and make sure no assumptions about it being even have crept in. I don't have a specific test in mind.
