### ISSUE TITLE
optionally return offset for psf image

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#37]
This is needed for the psf coaddition

**Comment by beckermr** [comment]
Not following what you want. The PSF is offset from the true center of the stamp with the subpixel offset of the input drawing location. Thus you can get the offset from the input location you asked for via `x - int(x+0.5), y - int(y+0.5)`.

**Comment by esheldon** [comment]
Yes, but I'm worried that conventions may be different in different scenarios.  E.g. what if the stack data uses a convention such that the offset is calculated differently?

**Comment by beckermr** [comment]
I am like 99% sure the stack follows FITS conventions.

**Comment by beckermr** [comment]
but go ahead and merge! :)

**Comment by esheldon** [comment]
I recall a "caveat emptor" in the SDSS code base, from rhl,  regarding pixel center conventions in SDSS, I think it defined it exactly 0.5 off from all other conventions I knew of.  Not sure if this made it into LSST.

**Comment by esheldon** [comment]
Here is the comment from rhl on the adaptive moments c code in sdss
```
* Note: this routine assumes that the _centre_ of a pixel is (0.0, 0.0)
 * which is not the SDSS convention. Caveat Lector.
```

**Comment by beckermr** [comment]
Pixel center at 0.0 is fits. Merge away!

**Comment by esheldon** [comment]
and here is the lsst documentation

https://pipelines.lsst.io/modules/lsst.afw.image/indexing-conventions.html

Relevant quote
```
Like NumPy and unlike FITS, LSST typically labels the center of the lower left pixel of an image (0, 0). Note that because we label the centers of pixels with integer coordinates, the exact coordinate bounding box of an image (which correspond to the edges of pixels) have half-integer values.
```

**Comment by esheldon** [comment]
So FITS convention is not followed, but they do not follow the SDSS convention

**Comment by beckermr** [comment]
Right ok. This means that fixing the offset to the internal comp is fine, but let's merge.
