### ISSUE TITLE
optical psf effects

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#56]
not sure how feasible this is

**Comment by beckermr** [comment]
I tried this and the convolutions were super slow.

If we switched to photon shooting this might help.

cc @rmjarvis

**Comment by esheldon** [comment]
As far as getting the shear calibration right, the issue is

1. do we have the right psf model
2. given the right psf model can metacal give us the right calibration?

For 1. we need dedicated simulations for testing the PSF modelling.

For 2. we might be able to take some shortcuts.  We just want something that has enough complexity.
