### ISSUE TITLE
cannot push to this repo

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#64]
I'm getting this type of error

```
> git push origin positions-in-cap
X11 forwarding request failed on channel 0
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 969 bytes | 969.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: Internal Server Error
To github.com:LSSTDESC/descwl-shear-sims.git
 ! [remote failure]  positions-in-cap -> positions-in-cap (remote failed to report status)
error: failed to push some refs to 'git@github.com:LSSTDESC/descwl-shear-sims.git'
```

I tested and I can push to descwl_coadds

**Comment by esheldon** [comment]
I tried with a fresh git clone and got the same failure

**Comment by esheldon** [comment]
I tried with a fresh git clone and got the same failure

**Comment by rmandelb** [comment]
GitHub has issues: https://www.githubstatus.com/

**Comment by esheldon** [comment]
interesting, I just checked there a minute ago and all was good :)

**Comment by beckermr** [comment]
you were pushing in the past and nothing has changed on the repo - closing

**Comment by esheldon** [comment]
I just tried again and it worked, although the github status page is still showing "We have identified the source of errors and are continuing to monitor recovery. "
