### ISSUE TITLE
only n-1 of the masks are showing up in the final coadd mask

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#67]

**Comment by esheldon** [comment]
There are three images with different rotations, but we only see two bleeds at different rotations.  This is generic, not just this example

![example](https://user-images.githubusercontent.com/621661/75350424-7de79100-5874-11ea-9243-7e9a36480ab7.png)

**Comment by beckermr** [comment]
Is this the coadding or the sims?

**Comment by esheldon** [comment]
that's a coadd mask plane.

just realized I accidentally put the issue here instead of descwl_coadds
