### ISSUE TITLE
the wldeblend images are on different zero points, but we are not passing this on

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#76]
We need to pass this information to the coadding some how, or put them onto the same system

I expect that the real DM processing forces all images to have the same zero point

**Comment by beckermr** [comment]
Wait what? How are the zero points different?

**Comment by esheldon** [comment]
What's the mag zero point?

**Comment by beckermr** [comment]
The issues title says the images are on different zero points. They should not be. I use whatever flux comes out of wldeblend so the zero point should always be the same, right?

**Comment by esheldon** [comment]
Here is the formula used:
```python
self.exposure_time*self.zero_point*10**(-0.4*(ab_magnitude-24))
```
The leading terms are explicitly taking the image *off* of the zero point of 24 and putting it onto some kind of instrumental zero point

**Comment by beckermr** [comment]
Yes but it is the same for **all** images, right?

Do you mean across different bands?

**Comment by esheldon** [comment]
Yes, different bands are gettinga different zero point and these are not close to 24, they range widely

**Comment by esheldon** [comment]
I plan to rescale them in the sim to zero point 30
