### ISSUE TITLE
make sim return exposures

### ISSUE THREAD

**Issue by esheldon** [LSSTDESC/descwl-shear-sims#84]
That is what we will get off disk when we convert to butler, better to make the sim deliver that.

Also, that is the only way we will be able to keep straight the mask bits.

**Comment by beckermr** [comment]
Not following here. The sims have some metadata associated with them that may not be amenable to an LSST exposure, right?

**Comment by esheldon** [comment]
We should return additional metadata, but use an exposure to store the image, bmask, variance plane.

**Comment by esheldon** [comment]
This has bumped up to high priority.  It is important that the downstream code in descwl_coadd takes in exposures so that we don't have different code paths for simluated and real data

**Comment by esheldon** [comment]
For variable psfs, we evaluating it at the center of the single epoch image and using that in a FixedPSF.  We had intended to evaluate it at the coadd center, so this seems like a bug.  I will try to fix, but I guess this means we are not very sensitive to this.

To make the code path consistent with what we'll do with real data, we need to return a mocked up DM psf and make sure to evaluate at the coadd center in the coadding code

**Comment by esheldon** [comment]
Note it looks like we are doing the right thing in the coadd code.

**Comment by beckermr** [comment]
For your previous comment where is that code snippet? I think this must be the rewritten code and not what I made originally.

**Comment by esheldon** [comment]
no doubt this is my mistake:  https://github.com/LSSTDESC/descwl-shear-sims/blob/master/descwl_shear_sims/sim/objlists.py#L87

**Comment by esheldon** [comment]
We need to also return a bbox rather than coadd sims, see  https://github.com/LSSTDESC/descwl_coadd/issues/45
